### ISSUE TITLE
after the new update all I am seeing only the link embedded text-whutbbcode

### ISSUE THREAD

**Issue by sfzaw** [hateradio/wbb#4]
after the new update all I am seeing only the link embedded text-whutbbcode
![123](https://user-images.githubusercontent.com/3743966/29266437-9781e02c-8106-11e7-9763-14ddc8c9f7e9.png)

**Comment by hateradio** [comment]
Which site is this for?

Also, any console output would be useful.

Chrome/Opera/Vivaldi: shift+ctrl+i or cmd+shift+i (I think for Mac)
Firefox: shift+ctrl+k
Safari: cmd+alt+i

**Comment by sfzaw** [comment]
tehconnection. chrome tempermonkey latest on win 7 starter.

[tehconnection.eu-1504049441028.txt](https://github.com/hateradio/wbb/files/1262026/tehconnection.eu-1504049441028.txt)
rename attach file to .log

**Comment by hateradio** [comment]
Release 5.1 should fix this issue.
