### ISSUE TITLE
Bug when you type preview or previewer in the editor

### ISSUE THREAD

**Issue by stephen147** [hateradio/wbb#5]
I found a bug when you type **preview** or **previewer** in the editor.

It hides the edit box.

**==Steps to reproduce==**
Type previewer in the textbox.
Type preview in the textbox.

1. Then press preview>Editor.
2. Click inside edit box.
3. Edit box disappears.

**==Fix==**
**I've changed line #1052:**
`if (/(?:preview)/i.test(el.value)) {`

to:
`if (/(?:^preview)/i.test(el.value)) {`

Works now after a restart of the browser.

**Comment by hateradio** [comment]
Fixed in 6.5

**Comment by stephen147** [comment]
Thanks.
